// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSNW43D4yo2yw7m0DcEI0iRcQRRn9c_s',
    appId: '1:780217844897:android:c97c844ee2a3bbf8eb5ce0',
    messagingSenderId: '780217844897',
    projectId: 'campus-safe-zone',
    storageBucket: 'campus-safe-zone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdsPPFKnzzi_j6WtWPWa3KBLyn3k70jhA',
    appId: '1:780217844897:ios:eefe877f12497af0eb5ce0',
    messagingSenderId: '780217844897',
    projectId: 'campus-safe-zone',
    storageBucket: 'campus-safe-zone.appspot.com',
    androidClientId: '780217844897-e675geh1vuvf622ivg0mlecdhqtuvi2j.apps.googleusercontent.com',
    iosClientId: '780217844897-p4pv0qddkk4o4155rrbrloal5at07c22.apps.googleusercontent.com',
    iosBundleId: 'com.example.aksustack',
  );
}
